### ISSUE TITLE
No wake from sleep

### ISSUE THREAD

**Issue by Storyspray** [laggykiller/hackintosh-gmk-nucbox2#1] opened 2022-03-26 00:54 UTC
Awesome job. Got this same EFI working on a BeeLink sei8 (almost identical specs).
Just wondering if you were able to get sleep working. My displays won't come back after sleep, and seems like keyboard may be the issue.
Thoughts?

**Comment by laggykiller** [comment] 2022-03-26 14:02
My system handles sleep without any problem.

> My displays won't come back after sleep

Are you sure that the problem is the display does not turn back on after sleep, instead of the system crashing?

A simple way to verify that the system did not crash, try to ssh ('remote login') into the machine after you wake it from sleep.

From my experience, if [iGPU is incorrectly patched](https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching), hardware acceleration does not work (quick way to check is to see if system recognize GPU in system information), and system can crash after waking from sleep.

> seems like keyboard may be the issue

Can you elaborate on this? Do you mean you cannot wake the computer with keyboard? Do you mean unplugging keyboard makes sleep work again? Why do you suspect the problem is with the keyboard? What is the model of your keyboard? Is the keyboard connected by USB, bluetooth, 2.4GHz, PS/2?

**Comment by Storyspray** [comment] 2022-03-26 14:36
Hey, thanks for all the info and response. I don't think the system is crashing, I really think it's just the displays. iGPU is correctly identified in system info. Wired USB keyboard and mouse, generic stuff from Walmart 😎. I'm away from the machine at the moment, but I'm going to play around with unplugging and replugging keyboard later this afternoon. I'll report back here.

**Comment by laggykiller** [comment] 2022-03-26 15:42
I think I understand what the issue is now. Is the hackintosh waking but display not turning on after one keypress? Does the display turn on after pressing keyboard one more time?

This issue is described in [here](https://dortania.github.io/OpenCore-Post-Install/usb/misc/keyboard.html) in Dortania guide. Method 1 (Add Wake Type Property) does not work, but method 2 (Create a fake ACPI Device) works.

I have updated the EFI by adding SSDT-USBW.aml and USBWakeFixup.kext, as well as changing the config.plist. Please check if this is the issue you are having and check if the update fixes your problem.

**Comment by Storyspray** [comment] 2022-03-26 16:04
Excellent. That's just what I was going to try actually. I should be able
to have a go this evening and I'll let you know for sure. Again, thanks for
the effort.

**Comment by Storyspray** [comment] 2022-03-26 19:18
Unfortunately, the new changes led to no boot for the sei8. Had to go back to the earlier Plist and delete the SSDT and Kexts. Booting again now but still no wake. Going to fool around with Dortania suggestions myself and will report here if I find a solution for sei8 folks.

**Comment by daliansky** [comment] 2022-05-09 08:57
Try it: https://github.com/daliansky/Beelink-SEI8-Hackintosh 

> Unfortunately, the new changes led to no boot for the sei8. Had to go back to the earlier Plist and delete the SSDT and Kexts. Booting again now but still no wake. Going to fool around with Dortania suggestions myself and will report here if I find a solution for sei8 folks.

**Comment by huangfengzhao** [comment] 2022-06-20 20:53
I have a Beelink SEi8 bought last year. It have been working great until yesterday, after I forced the mini PC power off, it can't restart anyway. WHen press the power button, it always seems like being sleep, no matter how I press the power button.
Is there any tips how to start my SEi8 mini PC?

**Comment by laggykiller** [comment] 2022-06-21 02:28
@huangfengzhao You hackintoshed Beelink SEi8 and this happened?
Either way, I don't know how I can help you, and I don't see how your issue is related to this repo.
Perhaps check for faulty power button? Try replacing power supply? Your machine is fried?
Good luck.

**Comment by laggykiller** [comment] 2022-06-21 02:30
It has been a month since @Storyspray last replied.
Since I do not have the machine on hand for supporting it, and @daliansky opened a repo specifically for Beelink SEi8, I am closing this issue.

**Closed as completed by laggykiller** 2022-06-21 02:30 UTC
